all:
  hosts:
    master:
      ansible_host: 51.250.76.113
      ansible_user: ubuntu
    worker-1:
      ansible_host: 89.169.167.250
      ip: 10.0.2.13
      access_ip: 89.169.167.250
    worker-2:
      ansible_host: 84.201.139.186
      ip: 10.0.2.22
      access_ip: 84.201.139.186
  children:
    kube_control_plane:
      hosts:
        master:
    kube_node:
      hosts:
        worker-1:
        worker-2:
    etcd:
      hosts:
        master:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
